name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: '>= 4.7.0'
  image_picker: ^1.1.2
  intl: ^0.19.0
  get: ^4.7.2
  google_fonts: ^6.3.1
  google_sign_in: ^5.0.3
  dio: ^5.9.0
  timeago: ^3.6.0

  # flutter_local_notifications: ^17.2.3
  # firebase_messaging: ^15.1.3
  # firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets: 
    - images/

flutter_icons:
  android: true
  image_path: "images/icons/icon.png"